### ISSUE TITLE
ERROR: !pystack: extension exception 0x80004005 "Unable to get type ID of 'PyInterpreterState'"

### ISSUE THREAD

**Issue by sparrowt** [SeanCline/PyExt#3] opened 2020-07-20 15:51 UTC
Hello and thank you again for such an incredibly useful extension.

I recently tried to use it again on a dump from 64-bit python 3.8.4 and got this message in windbg when running `!pystack`:
```
ERROR: !pystack: extension exception 0x80004005.
    "Unable to get type ID of 'PyInterpreterState'"
```

Is this fixed by fc47df7da6 (on master but not yet released)?
If so a new release with assets would be very much appreciated!

**Comment by SeanCline** [comment] 2020-07-20 16:44
It's possible that the issue is fixed but not yet released. Could you try [this build](https://ci.appveyor.com/project/SeanCline/pyext/builds/33721942)? It's from the [`pysetautointerpreterstate`](https://github.com/SeanCline/PyExt/tree/pysetautointerpreterstate) branch, which has a couple commits I've been meaning to merge to master.

If that takes care of it, then I'll do some housekeeping and update the releases.

**Comment by sparrowt** [comment] 2020-07-21 09:46
Thanks for the swift reply, using that build on the same dump it now fails with:
```
ERROR: !pystack: extension exception 0x80004005.
    "ExtRemoteTyped::Field: unable to retrieve field 'tstate_head' at 7ff952e5cb50"
```

**Comment by SeanCline** [comment] 2020-07-22 14:35
Hmm...
If I'm reading it right, the memory in your screenshot should be a pointer to heap allocated memory, but it doesn't look like it is.

Would you mind sending me the dump so I can see how it looks on my machine?
If the dump has proprietary information in it, we might have to come up with some other way to debug it.

**Comment by sparrowt** [comment] 2020-07-24 11:39
I'm afraid the dump is of a closed-source product so I can't really share it - however this should enable you to repro the crash:
```
py -3.8-64 -m virtualenv myenv
# activate myenv
pip install pywin32==227
```
 - then manually edit line 25 of `myenv\Lib\site-packages\win32comext\adsi\__init__.py` from `from adsi import *` to `from .adsi import *` otherwise it doesn't work... (don't ask)
 - run the below script using the python in `myenv`, with an appropriate LDAP address
```
import win32com.adsi as adsi

address = 'LDAP://DC=yourcompany,DC=net'

container = adsi.ADsOpenObject(address, None, None, 0x01, adsi.IID_IADsContainer)
searcher = container.QueryInterface(adsi.IID_IDirectorySearch)
search_handle = searcher.ExecuteSearch('(objectClass=*)', [])

# This crashes
searcher.GetColumn(search_handle, 'primaryGroupID')
```

**Comment by wbarnha** [comment] 2020-12-18 19:10
Hi there, I like your tool but I also encountered the same bug. I checked out your branch `pysetautointerpreterstate` and built it with the SDK for WIndows 8.1 and Windbg 32. Now, the new issue appears to be:
```
0:000> !pystack
Thread 0:
ERROR: !pystack: extension exception 0x80004005.
    "Unable to get type ID of 'PyFrameObject'"
```
The .DMP file was for a Python program I made in 3.9, but unfortunately I cannot share its contents.

**Comment by SeanCline** [comment] 2021-01-14 03:16
@wbarnha  Sometime in the recent months of 3.8/3.9 development, CPython [changed the name](](https://github.com/python/cpython/commit/7c59d7c9860cdbaf4a9c26c9142aebd3259d046e#diff-80b0f0cc7ce311d47e1134cb8615910f8a728ef96ff098f3635497efda485a00R47)) of the frame object from `PyFrameObject` to `_frame`. They've slowly been applying a similar change to their headers over the years, and I've just had to touch up PyExt when they do.

I've made the fix over on the `pysetautointerpreterstate` branch. If you get a chance, could you give it another try? The binaries are [over here](https://ci.appveyor.com/project/SeanCline/pyext/branch/pysetautointerpreterstate/job/g6p8vo7bnr0c8vmg/artifacts).

I'm currently looking at pull request #4 so hopefully I'll have those changes plus the `pysetautointerpreterstate` changes merged into the main branch pretty soon.

**Comment by wbarnha** [comment] 2021-03-16 22:51
It works now! Thank you very much, and sorry for the delayed response.

**Comment by sparrowt** [comment] 2021-04-14 11:20
I successfully used the latest release (v0.1.57) to debug a dump from 64-bit python 3.8.8 today - many thanks @SeanCline

**Closed** 2021-04-14 11:52 UTC

**Comment by SeanCline** [comment] 2021-04-14 16:19
@sparrowt Thanks for reporting back.
It's always nice to hear when things are working. I couldn't reproduce parts of what was reported, so I made the fixes blind and hoped for the best.
